import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f0f7ff",
          100: "#e0effe",
          200: "#bae0fd",
          300: "#7cc8fb",
          400: "#36adf7",
          500: "#0c92eb",
          600: "#0174c9",
          700: "#025ca1",
          800: "#064f85",
          900: "#0b426f",
          950: "#072a4a",
        },
        accent: {
          50: "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          300: "#c4b5fd",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
          900: "#4c1d95",
          950: "#2e1065",
        },
        surface: {
          light: "#ffffff",
          soft: "#f8fafc",
          dark: "#0f172a",
        },
        "on-secondary-fixed-variant": "#2d3c9c",
        "tertiary-fixed": "#ffdbca",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#773200",
        "outline": "#717785",
        "surface-container-low": "#f3f4f5",
        "on-error": "#ffffff",
        "on-background": "#191c1d",
        "on-primary-fixed-variant": "#004689",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed-dim": "#ffb68f",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-fixed": "#331100",
        "tertiary-container": "#c05500",
        "secondary": "#4755b6",
        "on-secondary-container": "#1b2b8c",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#0074db",
        "on-primary-fixed": "#001b3c",
        "secondary-container": "#8a99fe",
        "surface-tint": "#005eb3",
        "primary": "#005baf",
        "secondary-fixed-dim": "#bbc3ff",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-container": "#edeeef",
        "tertiary": "#994200",
        "primary-fixed-dim": "#a8c8ff",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#404754",
        "primary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fefcff",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#dfe0ff",
        "surface-dim": "#d9dadb",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#000d5f",
        "outline-variant": "#c0c6d6",
        "inverse-primary": "#a8c8ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-poppins)", "Poppins", "sans-serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "glass-gradient": "linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05))",
      },
      boxShadow: {
        "glass": "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
        "soft": "0 4px 20px -2px rgba(0, 0, 0, 0.05), 0 2px 10px -2px rgba(0, 0, 0, 0.03)",
        "premium": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "pulse-subtle": "pulse-subtle 4s ease-in-out infinite",
        "tilt": "tilt 10s infinite linear",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        tilt: {
          "0%, 50%, 100%": { transform: "rotate(0deg)" },
          "25%": { transform: "rotate(1deg)" },
          "75%": { transform: "rotate(-1deg)" },
        }
      },
    },
  },
  plugins: [],
};
export default config;

